/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { AddressAliasHelper } from "../AddressAliasHelper";

export class AddressAliasHelper__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<AddressAliasHelper> {
    return super.deploy(overrides || {}) as Promise<AddressAliasHelper>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): AddressAliasHelper {
    return super.attach(address) as AddressAliasHelper;
  }
  connect(signer: Signer): AddressAliasHelper__factory {
    return super.connect(signer) as AddressAliasHelper__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AddressAliasHelper {
    return new Contract(address, _abi, signerOrProvider) as AddressAliasHelper;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x4f69d734",
        type: "bytes32",
      },
    ],
    name: "c_0x4f69d734",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x609c610024600b82828239805160001a607314601757fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80634f2e0830146038575b600080fd5b606160048036036020811015604c57600080fd5b81019080803590602001909291905050506063565b005b5056fea264697066735822122055c691dc9c8cd57a5f02b78eb0f7823368b4068588821ba25d221238350bbba264736f6c634300060c0033";
