/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Base64 } from "../Base64";

export class Base64__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Base64> {
    return super.deploy(overrides || {}) as Promise<Base64>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Base64 {
    return super.attach(address) as Base64;
  }
  connect(signer: Signer): Base64__factory {
    return super.connect(signer) as Base64__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Base64 {
    return new Contract(address, _abi, signerOrProvider) as Base64;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x87a4cb07",
        type: "bytes32",
      },
    ],
    name: "c_0x87a4cb07",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x609c610024600b82828239805160001a607314601757fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80638ceb15d3146038575b600080fd5b606160048036036020811015604c57600080fd5b81019080803590602001909291905050506063565b005b5056fea2646970667358221220562d878411f2f07142c890d44b8817e901fe7bceb86bbf49087d964364ec579464736f6c634300060c0033";
