/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { DeevyMinter } from "../DeevyMinter";

export class DeevyMinter__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(deevyAddress: string, overrides?: Overrides): Promise<DeevyMinter> {
    return super.deploy(deevyAddress, overrides || {}) as Promise<DeevyMinter>;
  }
  getDeployTransaction(
    deevyAddress: string,
    overrides?: Overrides
  ): TransactionRequest {
    return super.getDeployTransaction(deevyAddress, overrides || {});
  }
  attach(address: string): DeevyMinter {
    return super.attach(address) as DeevyMinter;
  }
  connect(signer: Signer): DeevyMinter__factory {
    return super.connect(signer) as DeevyMinter__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DeevyMinter {
    return new Contract(address, _abi, signerOrProvider) as DeevyMinter;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "deevyAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deevyId",
        type: "uint256",
      },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "claimed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "deevy",
    outputs: [
      {
        internalType: "contract IDeevy",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516102b13803806102b18339818101604052602081101561003357600080fd5b5051600080546001600160a01b039092166001600160a01b031990921691909117905561024c806100656000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806350d97bc614610046578063aad3ec961461006a578063c884ef8314610098575b600080fd5b61004e6100d2565b604080516001600160a01b039092168252519081900360200190f35b6100966004803603604081101561008057600080fd5b506001600160a01b0381351690602001356100e1565b005b6100be600480360360208110156100ae57600080fd5b50356001600160a01b0316610201565b604080519115158252519081900360200190f35b6000546001600160a01b031681565b6123278111610123576040805162461bcd60e51b8152602060048201526009602482015268085513d2d15397d25160ba1b604482015290519081900360640190fd5b3360009081526001602052604090205460ff161561017a576040805162461bcd60e51b815260206004820152600f60248201526e1053149150511657d0d31052535151608a1b604482015290519081900360640190fd5b336000908152600160208190526040808320805460ff191690921790915581548151635569f64b60e11b81526001600160a01b038681166004830152602482018690529251929091169263aad3ec969260448084019382900301818387803b1580156101e557600080fd5b505af11580156101f9573d6000803e3d6000fd5b505050505050565b60016020526000908152604090205460ff168156fea26469706673582212208377d4094d0bbf405e7699731c331cdeb58102766de628de39c9e37f7406fc9464736f6c634300060c0033";
