/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DeevyMinterInterface extends ethers.utils.Interface {
  functions: {
    "c_0x7fb35f47(bytes32)": FunctionFragment;
    "claim(address,uint256)": FunctionFragment;
    "claimed(address)": FunctionFragment;
    "deevy()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_0x7fb35f47",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claimed", values: [string]): string;
  encodeFunctionData(functionFragment: "deevy", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "c_0x7fb35f47",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deevy", data: BytesLike): Result;

  events: {};
}

export class DeevyMinter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DeevyMinterInterface;

  functions: {
    c_0x7fb35f47(
      c__0x7fb35f47: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "c_0x7fb35f47(bytes32)"(
      c__0x7fb35f47: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    claim(
      account: string,
      deevyId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claim(address,uint256)"(
      account: string,
      deevyId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claimed(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "claimed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    deevy(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "deevy()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  c_0x7fb35f47(
    c__0x7fb35f47: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0x7fb35f47(bytes32)"(
    c__0x7fb35f47: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  claim(
    account: string,
    deevyId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claim(address,uint256)"(
    account: string,
    deevyId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claimed(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "claimed(address)"(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  deevy(overrides?: CallOverrides): Promise<string>;

  "deevy()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    c_0x7fb35f47(
      c__0x7fb35f47: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0x7fb35f47(bytes32)"(
      c__0x7fb35f47: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    claim(
      account: string,
      deevyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "claim(address,uint256)"(
      account: string,
      deevyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimed(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "claimed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    deevy(overrides?: CallOverrides): Promise<string>;

    "deevy()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    c_0x7fb35f47(
      c__0x7fb35f47: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0x7fb35f47(bytes32)"(
      c__0x7fb35f47: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(
      account: string,
      deevyId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claim(address,uint256)"(
      account: string,
      deevyId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    claimed(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "claimed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deevy(overrides?: CallOverrides): Promise<BigNumber>;

    "deevy()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    c_0x7fb35f47(
      c__0x7fb35f47: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0x7fb35f47(bytes32)"(
      c__0x7fb35f47: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      account: string,
      deevyId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claim(address,uint256)"(
      account: string,
      deevyId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claimed(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "claimed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deevy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "deevy()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
