/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DeevySetPropertiesInterface extends ethers.utils.Interface {
  functions: {
    "SET_NAME()": FunctionFragment;
    "getAlly(uint256)": FunctionFragment;
    "getArmament(uint256)": FunctionFragment;
    "getBody(uint256)": FunctionFragment;
    "getClass(uint256)": FunctionFragment;
    "getItem(uint256)": FunctionFragment;
    "getRelic(uint256)": FunctionFragment;
    "getTalent(uint256)": FunctionFragment;
    "getWeakness(uint256)": FunctionFragment;
    "setName()": FunctionFragment;
    "tokenURI(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "SET_NAME", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAlly",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getArmament",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBody",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClass",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getItem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRelic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTalent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWeakness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "SET_NAME", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAlly", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getArmament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBody", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getClass", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getItem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRelic", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTalent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWeakness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;

  events: {};
}

export class DeevySetProperties extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DeevySetPropertiesInterface;

  functions: {
    SET_NAME(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "SET_NAME()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getAlly(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getAlly(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getArmament(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getArmament(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getBody(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getBody(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getClass(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getClass(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getItem(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getItem(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getRelic(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getRelic(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getTalent(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getTalent(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getWeakness(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getWeakness(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setName(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "setName()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  SET_NAME(overrides?: CallOverrides): Promise<string>;

  "SET_NAME()"(overrides?: CallOverrides): Promise<string>;

  getAlly(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "getAlly(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getArmament(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getArmament(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getBody(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "getBody(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getClass(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "getClass(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getItem(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "getItem(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getRelic(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "getRelic(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getTalent(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "getTalent(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getWeakness(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getWeakness(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setName(overrides?: CallOverrides): Promise<string>;

  "setName()"(overrides?: CallOverrides): Promise<string>;

  tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "tokenURI(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    SET_NAME(overrides?: CallOverrides): Promise<string>;

    "SET_NAME()"(overrides?: CallOverrides): Promise<string>;

    getAlly(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "getAlly(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getArmament(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getArmament(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getBody(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "getBody(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getClass(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "getClass(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getItem(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "getItem(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getRelic(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "getRelic(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getTalent(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getTalent(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getWeakness(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getWeakness(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setName(overrides?: CallOverrides): Promise<string>;

    "setName()"(overrides?: CallOverrides): Promise<string>;

    tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    SET_NAME(overrides?: CallOverrides): Promise<BigNumber>;

    "SET_NAME()"(overrides?: CallOverrides): Promise<BigNumber>;

    getAlly(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAlly(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getArmament(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getArmament(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBody(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBody(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClass(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getClass(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getItem(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getItem(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRelic(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRelic(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTalent(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTalent(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWeakness(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getWeakness(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setName(overrides?: CallOverrides): Promise<BigNumber>;

    "setName()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    SET_NAME(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "SET_NAME()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAlly(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAlly(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getArmament(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getArmament(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBody(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBody(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getClass(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getClass(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getItem(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getItem(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRelic(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRelic(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTalent(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTalent(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWeakness(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getWeakness(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "setName()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
